spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080

app:
  seed-data: true

logging:
  level:
    com.fakegraph: DEBUG
    org.springframework.data.neo4j: DEBUG
